spring:
  application:
    name: database
  datasource:
    url: jdbc:mysql://localhost:3306/testingDB
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: po@localhost
    password: Log!n147
    #driver-class-name: com.mysql.cj.jdbc.Driver # Use the correct driver class name

  jpa:
    hibernate:
      ddl-auto: update # Or create, create-drop, validate, none (see explanation below)
    show-sql: true # Optional: To see the SQL queries Spring generates
    format-sql: true # Optional: To format the SQL queries for better