spring:
  application:
    name: database
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://dev-6gonohusakhjykxh.us.auth0.com/
#          audiences: https://dev-6gonohusakhjykxh.us.auth0.com/api/v2/
  datasource:
    url: jdbc:mysql://localhost:3306/testingDB
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: po@localhost
    password: Log!n147
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format-sql: true

logging:
  file:
    path: "."
    name: "application.log"
  level:
    root: DEBUG
#profiling