spring:
  application:
    name: database
  datasource:
    url: jdbc:mysql://localhost:3306/testingDB
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: po@localhost
    password: Log!n147


  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    format-sql: true